spring:
  flyway:
    locations: classpath:db/migration
    validate-migration-naming: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/test

